[tool.poetry]
name = "p6-doc-collection"
version = "0.1.0"
description = ""
authors = ["Pixel6 Team <digambar@pixel6.co>"]
readme = "README.md"
packages = [{include = "doc_collection"}]

[tool.poetry.dependencies]
python = ">=3.10, <4.0.0"
pydantic = "1.10.13"
cachetools = "^5.3.1"
types-cachetools = "^5.3.0.5"
jb-core = {path = "../../packages/jb-core", develop = true}
jb-storage = {path = "../../packages/jb-storage", develop = true}
aiohttp = "3.9.0"
certifi = "2023.7.22"
cryptography = "41.0.6"
urllib3 = "1.26.18"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.3.0"
flake8 = "^6.0.0"
poethepoet = "^0.20.0"
pytest = "^7.3.1"
pytest-asyncio = "^0.21.0"
faker = "^18.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poe.tasks.lint]
shell = """
black jugalbandi tests
flake8 jugalbandi tests
mypy jugalbandi tests
"""
interpreter = "bash"
help = "format, lint, typecheck"


[tool.poe.tasks.test]
cmd = "python -m pytest -vv -o log_cli=1 -o log_cli_level=INFO -W 'ignore::DeprecationWarning' $FILE"
args = [{name="FILE", default="tests", positional=true}]
help = "run tests using pytest"
